### ISSUE TITLE
JOSS review: Add GitHub installation instructions

### ISSUE THREAD

**Issue by kanishkan91** [PIK-LPJmL/lpjmlkit#1]
Authors have added detailed installation instructions for the CRAN version of the package. However, Since this package is available on GitHub, I would recommend the authors also add instructions on how users can directly install the package from GitHub. 

I was able to install the same using- `devtools::install_github("PIK-LPJmL/lpjmlkit",build_vignettes = TRUE)`

I would recommend authors add instructions for the same in the README. 

https://github.com/openjournals/joss-reviews/issues/5447

**Comment by jnnsbrr** [comment]
As described in issue #3 this is also part of an automatically build README which is why I cannot change it in the installation part :-/
