### ISSUE TITLE
JOSS review: Comments on documentation, README

### ISSUE THREAD

**Issue by kanishkan91** [PIK-LPJmL/lpjmlkit#3]
- [ ] In the contribution section, please indicate that users are encouraged to report issues on GitHub
- [ ] I would recommend removing the "citation" since once the JOSS paper is published, you will just add a button on the README

https://github.com/openjournals/joss-reviews/issues/5447

**Comment by jnnsbrr** [comment]
Dear @kanishkan91, unfortunately parts of the README are automatically build and standardized (including citation and contributing) using an R library at our Institute (https://github.com/pik-piam/lucode2) which follows a common structure (https://github.com/orgs/pik-piam/repositories) I cannot directly change.  
But I saw that the CONTRIBUTING.md file was missing, so its now included and provides detailed instructions.
