### ISSUE TITLE
JOSS review: Unable to test functions in vignettes since "outputs" folder is not available 

### ISSUE THREAD

**Issue by kanishkan91** [PIK-LPJmL/lpjmlkit#4]
When I try to run `runoff <- read_io("./output/mrunoff.bin.json")` it does not work since the output folder does not exist. It does exist within the tests folder. This may confuse new users. I would recommend adding a sample_data folder or the outputs folder itself to the root directory to resolve this. Or maybe mention that the sample data needs to be downloaded or something? 

https://github.com/openjournals/joss-reviews/issues/5447

**Comment by jnnsbrr** [comment]
Thanks @kanishkan91. Unfortunately LPJmL ouput data is quite large in size. Therefore I created a zenodo publication with some example data that can be used - which is linked to at the [Start of the LPJmLData vignette](https://github.com/PIK-LPJmL/lpjmlkit/blob/051c06930a658347c72765cc03502cde17ec0bc6/vignettes/lpjml-data.Rmd#L32) where the data is useful.
> Example data files can be downloaded from https://doi.org/10.5281/zenodo.12915168
